name: awwab
description: "Awwab Flutter application foundation."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  google_fonts: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/awwab_character_main.jpg
    - assets/images/awwab_character.png
    - assets/images/awwab_aura_ring.png
